// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnvfhraekgwlkmpzxhqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndudmZocmFla2d3bGttcHp4aHF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3ODEyMDUsImV4cCI6MjA2MzM1NzIwNX0.xSW4t0fZo3ZbB7ei3oxC4uoJogLgyCo5Mvv9yC8bYjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);